/** @type {import('tailwindcss').Config} */
export default {
  darkMode: "class",
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "on-secondary-fixed-variant": "#004e5a",
        "primary-fixed-dim": "#d2bbff",
        "on-tertiary": "#490081",
        "background": "#0c1324",
        "on-tertiary-container": "#f2e0ff",
        "surface": "#0c1324",
        "outline": "#958da1",
        "surface-tint": "#d2bbff",
        "surface-dim": "#0c1324",
        "error": "#ffb4ab",
        "on-tertiary-fixed": "#2c0051",
        "error-container": "#93000a",
        "outline-variant": "#4a4455",
        "on-secondary-fixed": "#001f25",
        "on-primary-fixed": "#25005a",
        "surface-container-high": "#23293c",
        "secondary-container": "#00cbe6",
        "secondary-fixed": "#a2eeff",
        "primary": "#d2bbff",
        "surface-bright": "#33394c",
        "secondary-fixed-dim": "#2fd9f4",
        "on-primary": "#3f008e",
        "on-error-container": "#ffdad6",
        "surface-variant": "#2e3447",
        "on-secondary-container": "#00515d",
        "inverse-surface": "#dce1fb",
        "inverse-primary": "#732ee4",
        "on-primary-container": "#ede0ff",
        "primary-container": "#7c3aed",
        "inverse-on-surface": "#2a3043",
        "on-background": "#dce1fb",
        "tertiary-fixed": "#f0dbff",
        "tertiary-fixed-dim": "#ddb8ff",
        "surface-container-highest": "#2e3447",
        "surface-container-low": "#151b2d",
        "tertiary": "#ddb8ff",
        "on-tertiary-fixed-variant": "#62259b",
        "surface-container-lowest": "#070d1f",
        "surface-container": "#191f31",
        "on-secondary": "#00363e",
        "tertiary-container": "#844abe",
        "on-error": "#690005",
        "primary-fixed": "#eaddff",
        "on-surface-variant": "#ccc3d8",
        "secondary": "#5de6ff",
        "on-surface": "#dce1fb",
        "on-primary-fixed-variant": "#5a00c6",
      },
      fontFamily: {
        headline: ["Manrope", "sans-serif"],
        body: ["Inter", "sans-serif"],
        label: ["Inter", "sans-serif"],
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
    },
  },
  plugins: [],
};
